/**
 * `iris transcribe <file> --on <node>` (#188318 half 2, epic #188696 O5): hand PRIVATE audio
 * to a Hive node you own and transcribe it there — never to a cloud STT.
 *
 * Why this and not the Hive task transport: the audio moves over the user's own Tailscale mesh
 * by scp (the same path as `iris hive fs push`, sha256-verified both ends), so the bytes never
 * pass through an IRIS server or any provider. The task transport is not byte-safe anyway (see
 * hive-tailscale.ts) and would put the audio in our relay.
 *
 * The node runs with IRIS_TRANSCRIPTION_POLICY=sovereign whatever CLI it has — that ceiling has
 * existed since epic #182784, so even a node that predates --private fails closed rather than
 * uploading. `--private` is added only when the node's CLI knows it: a strict yargs that sees an
 * unknown flag prints help and exits 0, which would read as a successful empty run.
 *
 * Kept free of yargs and of process.exit so the whole round trip can be tested with the remote
 * faked out — the decisions (what to run, what to accept back, what to delete) live here.
 */

import { basename } from "path"
import { randomBytes } from "crypto"
import type { RemoteResult, TransferOutcome, SshTarget } from "../cmd/hive-tailscale"

export interface NodeIO {
  run: (t: SshTarget, command: string, timeoutMs?: number) => Promise<RemoteResult>
  push: (t: SshTarget, localPath: string, remoteDir: string) => Promise<TransferOutcome>
}

export type OnNodeResult =
  | { ok: true; text: string; provider: string; remoteSha256: string | null }
  | { ok: false; error: string; stage: "push" | "probe" | "transcribe" | "verify" }

/** Single-quote for a POSIX shell. Paths here are generated by us, but quote them anyway. */
function q(s: string): string {
  return `'${s.replace(/'/g, `'\\''`)}'`
}

/**
 * The CLI's --json output shares stdout with the intro/outro lines, so take the LAST JSON object
 * that carries a provider or an error. Exported for the test.
 */
export function lastJsonObject(stdout: string): Record<string, any> | null {
  const starts: number[] = []
  for (let i = 0; i < stdout.length; i++) if (stdout[i] === "{") starts.push(i)
  for (let k = starts.length - 1; k >= 0; k--) {
    const tail = stdout.slice(starts[k])
    // Grow the candidate to each closing brace until one parses.
    for (let j = tail.indexOf("}"); j !== -1; j = tail.indexOf("}", j + 1)) {
      try {
        const obj = JSON.parse(tail.slice(0, j + 1))
        if (obj && typeof obj === "object" && ("provider" in obj || "error" in obj)) return obj
      } catch {
        /* keep growing */
      }
    }
  }
  return null
}

/** Only an on-device engine counts. Anything else coming back means the node did NOT keep it. */
export function isOnDeviceProvider(provider: unknown): boolean {
  return typeof provider === "string" && /whisper/i.test(provider) && /local/i.test(provider)
}

export async function transcribeOnNode(
  t: SshTarget,
  absPath: string,
  io: NodeIO,
  opts: { language?: string; timeoutMs?: number } = {},
): Promise<OnNodeResult> {
  // A fresh 0700 directory per take, removed in finally — a node that transcribes for others must
  // not accumulate their audio.
  const dir = `/tmp/iris-private-${randomBytes(8).toString("hex")}`
  const remoteFile = `${dir}/${basename(absPath)}`
  const PATHS = `PATH="$HOME/.iris/bin:/usr/local/bin:/opt/homebrew/bin:$PATH"`

  try {
    const mk = await io.run(t, `mkdir -m 700 ${q(dir)}`)
    if (!mk.ok) return { ok: false, stage: "push", error: `could not create a private directory on the node: ${mk.stderr.trim()}` }

    const pushed = await io.push(t, absPath, dir)
    if (!pushed.ok || !pushed.verified) {
      return { ok: false, stage: "push", error: pushed.error ?? "the copy on the node did not match (sha256)" }
    }

    // Does this node's CLI know --private? Ask its help rather than its version: the flag is
    // the thing we depend on, and a version number is a proxy for it.
    const help = await io.run(t, `${PATHS} iris transcribe --help 2>&1`, 60_000)
    if (!help.ok && !help.stdout) return { ok: false, stage: "probe", error: `no iris CLI answering on the node: ${help.stderr.trim().slice(0, 200)}` }
    const knowsPrivate = /--private\b/.test(help.stdout)

    const flags = ["--json", ...(knowsPrivate ? ["--private"] : []), ...(opts.language ? ["--language", q(opts.language)] : [])]
    const cmd =
      `${PATHS} IRIS_TRANSCRIPTION_POLICY=sovereign DO_NOT_TRACK=1 ` +
      `iris transcribe ${q(remoteFile)} ${flags.join(" ")} 2>/dev/null`
    const r = await io.run(t, cmd, opts.timeoutMs ?? 30 * 60_000)

    const out = lastJsonObject(r.stdout)
    if (!out) return { ok: false, stage: "transcribe", error: `the node returned no transcript (exit ${r.code})` }
    if (out.error || out.success === false) return { ok: false, stage: "transcribe", error: String(out.message ?? out.error) }

    // Defence in depth: the node ran under sovereign, so this cannot be a cloud provider — but
    // "cannot" is a claim about code on another machine. Refuse a transcript that says otherwise.
    if (!isOnDeviceProvider(out.provider)) {
      return { ok: false, stage: "verify", error: `the node reported provider '${out.provider}', which is not on-device — transcript discarded` }
    }
    const text = String(out.text ?? "")
    if (!text.trim()) return { ok: false, stage: "transcribe", error: "the node returned an empty transcript" }
    return { ok: true, text, provider: String(out.provider), remoteSha256: pushed.remoteSha256 }
  } finally {
    await io.run(t, `rm -rf ${q(dir)}`).catch(() => {})
  }
}
