// ============================================================================
// Where `iris playbook sync` lands a team's playbooks, beyond Claude Code (#186212).
//
// A team's shared library already existed (`playbook publish` / `install`) and `sync` already put
// it where Claude Code reads it (.claude/skills). Other agents on the same repo saw nothing:
// Cursor reads .cursor/rules/*.mdc, and Codex, OpenCode and most others read AGENTS.md. So the
// same rules reached one tool out of three. These render the SAME replica `sync` writes for
// Claude into the other two shapes — one source, three readers.
// ============================================================================

export type SyncTarget = "claude" | "cursor" | "agents"
export const ALL_TARGETS: SyncTarget[] = ["claude", "cursor", "agents"]
export const GENERATED_MARKER = "<!-- AUTO-GENERATED by iris playbook sync — do not edit -->"
const BLOCK_START = "<!-- iris-playbooks:start — generated by `iris playbook sync --target agents`; edits inside are replaced -->"
const BLOCK_END = "<!-- iris-playbooks:end -->"

/** "cursor,agents" | "all" | undefined → targets. Unknown names are an error, not silently dropped. */
export function parseTargets(raw: string | undefined): SyncTarget[] {
  if (!raw) return ["claude"]
  const parts = raw.split(",").map((s) => s.trim().toLowerCase()).filter(Boolean)
  if (parts.includes("all")) return [...ALL_TARGETS]
  const bad = parts.filter((p) => !(ALL_TARGETS as string[]).includes(p))
  if (bad.length) throw new Error(`unknown --target ${bad.join(", ")} (use: ${ALL_TARGETS.join(", ")}, all)`)
  return [...new Set(parts)] as SyncTarget[]
}

/** The replica's body without its YAML frontmatter and without the generated marker. */
function replicaBody(replica: string): string {
  const m = replica.match(/^---\n[\s\S]*?\n---\n/)
  return (m ? replica.slice(m[0].length) : replica).replace(GENERATED_MARKER, "").trim()
}

/**
 * A Cursor project rule. `alwaysApply: false` + a description = an "agent requested" rule: Cursor
 * loads it when the task matches the description, the way Claude Code loads a skill — so a library
 * of 100 playbooks does not ride along in every prompt.
 */
export function toCursorRule(replica: string, description: string): string {
  return ["---", `description: ${JSON.stringify(String(description ?? ""))}`, "alwaysApply: false", "---", "", GENERATED_MARKER, "", replicaBody(replica), ""].join("\n")
}

/** A file we may overwrite: absent, or one we generated. A hand-written rule is left alone. */
export function isGenerated(existing: string | null): boolean {
  return existing === null || existing.includes(GENERATED_MARKER)
}

/**
 * Insert or replace the playbook index inside AGENTS.md, leaving everything outside the markers
 * exactly as written. AGENTS.md is usually hand-maintained, so this owns one fenced block only.
 */
export function upsertAgentsBlock(existing: string | null, entries: { name: string; description: string }[]): string {
  const lines = [
    BLOCK_START,
    "## Team playbooks",
    "",
    "Shared procedures for this repo. Read the full text before doing one of these jobs:",
    "`.cursor/rules/<name>.mdc`, `.claude/skills/<name>/SKILL.md`, or run `iris playbook run <name>`.",
    "",
    ...[...entries].sort((a, b) => a.name.localeCompare(b.name)).map((e) => `- **${e.name}** — ${String(e.description ?? "").replace(/\s+/g, " ").trim()}`),
    BLOCK_END,
  ]
  const block = lines.join("\n")
  if (!existing) return block + "\n"
  const s = existing.indexOf(BLOCK_START.slice(0, 26))
  const e = existing.indexOf(BLOCK_END)
  if (s !== -1 && e > s) return existing.slice(0, s) + block + existing.slice(e + BLOCK_END.length)
  return existing.replace(/\s*$/, "") + "\n\n" + block + "\n"
}
