import { cmd } from "./cmd"
import * as prompts from "./clack"
import { UI } from "../ui"
import { dim, bold, success, highlight } from "./iris-api"
import { homedir } from "os"
import { join } from "path"

// ============================================================================
// Client-safe CLAUDE.md content — no internal infra details
// ============================================================================

function generateClaudeMd(): string {
  return `# CLAUDE.md — IRIS CLI Guide

This file was generated by \`iris claude init\`. It gives Claude Code context for working with the IRIS platform.

## Quick Start

\`\`\`bash
iris config          # Verify SDK is connected
iris doctor          # Full health check before starting work
\`\`\`

## Command Categories

\`\`\`bash
iris guide <topic>        # Detailed help for a category
iris <command> --help     # Help for a specific command
\`\`\`

**Topics:** crm, atlas, knowledge, pages, agents, integrations, entities, communication, finance, compute, system, core

## Most-Used Commands

### Knowledge & Content
\`\`\`bash
iris bloqs list                          # List all bloqs
iris bloqs get <id>                      # Show bloq with lists
iris bloqs add-item <bloqId> <listId>    # Add item to a list
iris bloqs create --title "Name"         # Create new bloq
iris memory list                         # Alias for bloqs list
\`\`\`

### CRM & Sales
\`\`\`bash
iris leads list                          # List leads
iris leads get <id>                      # Lead details
iris deals list                          # Active payment gates
iris invoices list                       # View invoices
iris outreach list                       # Outreach strategies
\`\`\`

### Pages (Genesis Page Builder)
\`\`\`bash
iris pages list                          # List composable pages
iris pages get <slug>                    # View page JSON
iris pages push <slug>                   # Upload local JSON to remote
iris pages pull <slug>                   # Download remote to local
iris pages diff <slug>                   # Compare local vs remote
iris pages publish <slug>                # Publish a page
\`\`\`

### Agents & Automation
\`\`\`bash
iris chat <agent_id>                     # Chat with an agent
iris agents list                         # List platform agents
iris schedules list                      # View scheduled jobs
iris workflows list                      # View workflows
iris automation list                     # V6 automations
\`\`\`

### Integrations
\`\`\`bash
iris integrations list                   # Show available integrations
iris list-connected                      # Show connected integrations
iris connect <service>                   # Connect via OAuth or API key
\`\`\`

### Entity Management
\`\`\`bash
iris brands list                         # List brands
iris products list                       # List products
iris services list                       # List services
iris programs list                       # List programs
iris opportunities list                  # List opportunities
\`\`\`

### Diagnostics & System
\`\`\`bash
iris doctor                              # Full system health check
iris doctor --json                       # Machine-readable health
iris bug report --title "..." --description "..." --severity <high|medium|low>
iris bug list                            # View open bugs
iris config                              # View SDK configuration
iris sdk:call --list                     # Show all available API methods
\`\`\`

## SDK Proxy (Advanced)

For any endpoint not wrapped in a named command:

\`\`\`bash
iris sdk:call --list                          # Show all available resource.method pairs
iris sdk:call bloqs.share bloqId=357          # Call any endpoint dynamically
iris sdk:call bloqs.items.create bloqId=358 listId=1250 title="New item"
\`\`\`

## How-To Recipes

Step-by-step guides for common workflows:

\`\`\`bash
iris how-to list                         # List all recipes
iris how-to view <name>                  # Read a recipe
\`\`\`

## Key Concepts

- **Bloq** — A knowledge base. All data is scoped to a bloq. Bloqs contain lists, and lists contain items.
- **Agent** — An AI assistant with customizable capabilities, model, and integrations.
- **Page** — A composable landing page built from JSON component definitions (Genesis page builder).
- **Integration** — A connected external service (Google, Slack, Stripe, etc.).
- **Workflow** — A multi-step automation that orchestrates agents, integrations, and actions.
- **Schedule** — A recurring job (heartbeat, task dispatch, newsletter, etc.).

## Important Rules

- **AI Models:** Never use GPT-3.5-turbo. Use \`gpt-5-nano\`, \`gpt-4.1-nano\`, or \`gpt-4o-mini\`.
- **Bug Reporting:** Always use \`iris bug report\` to file bugs. Check \`iris bug list\` first.
- **Health Checks:** Run \`iris doctor\` before starting any session to verify connectivity.
- **SDK calls:** Use \`iris sdk:call --list\` to discover available API methods before writing raw HTTP calls.
`
}

// ============================================================================
// Commands
// ============================================================================

const ClaudeInitCommand = cmd({
  command: "init",
  aliases: ["readme", "setup"],
  describe: "generate a CLAUDE.md in the current project for Claude Code cowork sessions",
  builder: (y) =>
    y.option("output", {
      alias: "o",
      type: "string",
      describe: "output path (default: ./.claude/CLAUDE.iris.md)",
    }).option("force", {
      alias: "f",
      type: "boolean",
      describe: "overwrite existing file",
      default: false,
    }),
  async handler(args) {
    UI.empty()
    prompts.intro("◈  IRIS Claude Cowork Setup")

    const fs = await import("fs")
    const path = await import("path")

    const outputPath = (args as any).output || path.join(process.cwd(), ".claude", "CLAUDE.iris.md")
    const outputDir = path.dirname(outputPath)

    // Check if file already exists
    if (fs.existsSync(outputPath) && !(args as any).force) {
      console.log()
      console.log(`  ${dim("File already exists:")} ${outputPath}`)
      console.log(`  ${dim("Use")} ${highlight("--force")} ${dim("to overwrite")}`)
      console.log()
      prompts.outro(dim("No changes made"))
      return
    }

    // Ensure directory exists
    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true })
    }

    // Write the file
    const content = generateClaudeMd()
    fs.writeFileSync(outputPath, content, "utf-8")

    console.log()
    console.log(`  ${success("✓")} ${bold("CLAUDE.iris.md")} written to ${dim(outputPath)}`)
    console.log()
    console.log(`  ${dim("Claude Code will now automatically pick up IRIS CLI context")}`)
    console.log(`  ${dim("when working in this directory.")}`)
    console.log()
    console.log(`  ${dim("To update later:")} ${highlight("iris claude init --force")}`)
    console.log()

    prompts.outro(dim("Ready for cowork"))
  },
})

const ClaudeShowCommand = cmd({
  command: "show",
  aliases: ["view", "print"],
  describe: "print the CLAUDE.md content to stdout",
  builder: (y) => y,
  async handler() {
    console.log(generateClaudeMd())
  },
})

// ── Root command ─────────────────────────────────────────────────────────────

export const PlatformClaudeCommand = cmd({
  command: "claude",
  aliases: ["cowork"],
  describe: "generate CLAUDE.md for Claude Code cowork sessions",
  builder: (yargs) =>
    yargs
      .command(ClaudeInitCommand)
      .command(ClaudeShowCommand)
      .demandCommand(),
  async handler() {},
})
